apiVersion: v1
kind: Deployment
metadata:
  name: postgress-deployment
  label:
   app: demo-voting-app
spec:
  replicas: 1
  selector:
   matchLabels:
    name: postgres-pod
    app: demo-voting-app
  template:
    metadata:
     name: postgres-pod
     labels:
      name: postgres-pod
      app: demo-voting-app

    spec:
     containers:
      - name: postgres
        image: coreroller/postgres
        ports:
        - containerPort: 5432
